### ISSUE TITLE
Use of db.sqlite

### ISSUE THREAD

**Issue by ghost** [mdomnita/LyndaCaptionToSrtConvertor#6]
Firstly, thanks for this awesome work. However, when I try to decrypt the .CAPTION files using this script, it results in captions having random. I hope this could also use something like Hack-root's LyndaDecrytor which uses /DB to place the files in proper folders and along with their corresponding filenames.

**Comment by mdomnita** [comment]
Hello Sarthak,
I worked on a fork of Hack-root's https://github.com/h4ck-rOOt/Lynda-Decryptor which I think is in another repo of mine and it can be used just like that but it also gives subtitles. Also, this feature was merged in the Lynda Decyptor project at some time. I did not test it lately as I don't have a Lynda subscrpition anymore but I think it still works fine.
Matei
